---
- hosts: localhost
  gather_facts: false
  no_log: true

  tasks:

  - name: Define fact holding the current timestamp
    set_fact:
      output_fn: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') + '.log' }}"

- hosts: all
  gather_facts: no
  no_log: true

  tasks:

  - name: Loop through all accounts
    include_tasks: process-host.yml
    with_items: "{{ accounts }}"

- hosts: localhost
  gather_facts: false
  no_log: true

  tasks:

  - name: Generate overview fact containing list of hosts and accounts changed
    set_fact:
      overview: "{{ overview | default('') + item + ':' + hostvars[item]['changed_users'] | join(',') + '\n' }}"
    when: hostvars[item]['changed_users'] is defined
    with_items: "{{ hostvars }}"

  - name: Write the overview fact to file
    copy:
      content: "{{ overview }}"
      dest: "{{ output_fn }}"
    when: overview is defined
